env:
  browser: yes
  commonjs: yes
extends: 'eslint:recommended'
globals:
  p2: no
  Phaser: no
  PIXI: no
rules:
  indent:
    - 'off'
  linebreak-style:
    - warn
    - unix
  no-shadow:
    - error
  no-unused-vars:
    - warn
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
